name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name : Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Lint with flake8
        run: flake8 dags/raw/sec/dag_bronze_company_cik.py --max-line-length=120
